## Config file

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: hibalazs
description: Personal collection of useful information.

show_downloads: false
